source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.1'

gem 'active_model_serializers', '~> 0.10.0'
gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'config'
gem 'devise'
gem 'devise_token_auth'
gem 'lockbox'
gem 'mysql2', '~> 0.5'
gem 'parser', '~> 3.0'
gem 'rack-cors'
gem 'rails', '~> 6.1.3', '>= 6.1.3.2'
gem 'redis', '~> 4.0'
gem 'ridgepole'
gem 'unicorn'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'factory_bot'
  # FIXME ruby 3.0.1非対応のためコメントアウト airbnbがダメ？
  # gem 'rubocop-airbnb'
  gem 'rspec-rails'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'pry-rails'
  gem 'spring'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
